apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: webapp # going to manage any pod where the label "app:webapp" is set IMPORTANT: for service, the pod label is relevant
  replicas: 2
  template: # templates for the pod
    metadata:
      # name: webapp -> This is not needed here. Name is manged by the ReplicaSet
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: richardchesterwood/k8s-fleetman-webapp-angular:release0

# document separator - yaml specific
---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels:
    app: queue
    release: "1"
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1
