apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  # This defines, which pods are going to be represented by this service
  # The service becomes a network endpoint for either other services
  # or maybe external users to connect to (eg browser)
  selector:
    app: webapp
  # which ports do we expose through this service
  # We accept traffic on port 80 ; and we forward that traffic to port 80 on the container
  ports:
    - name: http # this is just a helpful label o what traffic this is going to be
      port: 80
      targetPort: 80 # usually this defaults to the "port" when not specified ie 80:80
      # Only for services of type NodePort; The port, our webapp is going to be accessible thorugh the browser
      # K8s allows you to use any port greater than 30000
      nodePort: 30080

  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  selector:
    app: queue
    release: "1"
  ports:
    - name: http
      port: 8161
      nodePort: 30010
  type: NodePort
